definitions:
  merchant.CreateAPIKeyRequest:
    properties:
      app_description:
        maxLength: 100
        type: string
      app_homepage_url:
        maxLength: 100
        type: string
      app_name:
        maxLength: 20
        type: string
      redirect_uri:
        maxLength: 100
        type: string
    required:
    - app_homepage_url
    - app_name
    - redirect_uri
    type: object
  merchant.UpdateAPIKeyRequest:
    properties:
      app_description:
        maxLength: 100
        type: string
      app_homepage_url:
        maxLength: 100
        type: string
      app_name:
        maxLength: 20
        type: string
      redirect_uri:
        maxLength: 100
        type: string
    type: object
  model.PayLevel:
    enum:
    - 0
    - 1
    - 2
    - 3
    format: int32
    type: integer
    x-enum-varnames:
    - PayLevelFree
    - PayLevelBasic
    - PayLevelStandard
    - PayLevelPremium
  oauth.CallbackRequest:
    properties:
      code:
        type: string
      state:
        type: string
    type: object
  order.TransactionListRequest:
    properties:
      client_id:
        type: string
      endTime:
        type: string
      page:
        minimum: 1
        type: integer
      page_size:
        maximum: 100
        minimum: 1
        type: integer
      startTime:
        type: string
      status:
        enum:
        - success
        - pending
        - failed
        - expired
        - disputing
        - refund
        - refunded
        type: string
      type:
        enum:
        - receive
        - payment
        - transfer
        - community
        type: string
    type: object
  payment.CreateOrderRequest:
    properties:
      amount:
        type: number
      order_name:
        maxLength: 64
        type: string
      remark:
        maxLength: 200
        type: string
    required:
    - amount
    - order_name
    type: object
  payment.PayOrderRequest:
    properties:
      order_no:
        type: string
      pay_key:
        maxLength: 10
        type: string
    required:
    - order_no
    - pay_key
    type: object
  system_config.CreateSystemConfigRequest:
    properties:
      description:
        maxLength: 255
        type: string
      key:
        maxLength: 64
        type: string
      value:
        maxLength: 255
        type: string
    required:
    - key
    - value
    type: object
  system_config.UpdateSystemConfigRequest:
    properties:
      description:
        maxLength: 255
        type: string
      value:
        maxLength: 255
        type: string
    required:
    - value
    type: object
  user.UpdatePayKeyRequest:
    properties:
      pay_key:
        maxLength: 10
        type: string
    required:
    - pay_key
    type: object
  user_pay_config.CreateUserPayConfigRequest:
    properties:
      daily_limit:
        type: integer
      fee_rate:
        type: number
      level:
        $ref: '#/definitions/model.PayLevel'
      max_score:
        type: integer
      min_score:
        minimum: 0
        type: integer
    required:
    - fee_rate
    - level
    - min_score
    type: object
  user_pay_config.UpdateUserPayConfigRequest:
    properties:
      daily_limit:
        type: integer
      fee_rate:
        type: number
      max_score:
        type: integer
      min_score:
        minimum: 0
        type: integer
    required:
    - fee_rate
    - min_score
    type: object
  util.ResponseAny:
    properties:
      data: {}
      error_msg:
        example: ""
        type: string
    type: object
info:
  contact: {}
  title: LINUX DO PAY
  version: 0.1.0
paths:
  /api/v1/admin/system-configs:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - admin
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/system_config.CreateSystemConfigRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - admin
  /api/v1/admin/system-configs/{key}:
    delete:
      parameters:
      - description: 配置键
        in: path
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - admin
    get:
      parameters:
      - description: 配置键
        in: path
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - admin
    put:
      consumes:
      - application/json
      parameters:
      - description: 配置键
        in: path
        name: key
        required: true
        type: string
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/system_config.UpdateSystemConfigRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - admin
  /api/v1/admin/user-pay-configs:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - admin
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user_pay_config.CreateUserPayConfigRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - admin
  /api/v1/admin/user-pay-configs/{id}:
    delete:
      parameters:
      - description: 配置ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - admin
    get:
      parameters:
      - description: 配置ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - admin
    put:
      consumes:
      - application/json
      parameters:
      - description: 配置ID
        in: path
        name: id
        required: true
        type: string
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user_pay_config.UpdateUserPayConfigRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - admin
  /api/v1/health:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - health
  /api/v1/merchant/api-keys:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - merchant
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/merchant.CreateAPIKeyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - merchant
  /api/v1/merchant/api-keys/{id}:
    delete:
      parameters:
      - description: API Key ID
        format: int64
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - merchant
    get:
      parameters:
      - description: API Key ID
        format: int64
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - merchant
    put:
      consumes:
      - application/json
      parameters:
      - description: API Key ID
        format: int64
        in: path
        name: id
        required: true
        type: integer
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/merchant.UpdateAPIKeyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - merchant
  /api/v1/merchant/payment:
    post:
      consumes:
      - application/json
      parameters:
      - description: 支付订单请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/payment.PayOrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - payment
  /api/v1/merchant/payment/order:
    get:
      consumes:
      - application/json
      parameters:
      - description: 订单号
        in: query
        name: order_no
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - payment
  /api/v1/merchant/payment/orders:
    post:
      consumes:
      - application/json
      parameters:
      - description: Bearer {ClientID}:{ClientSecret}
        in: header
        name: Authorization
        required: true
        type: string
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/payment.CreateOrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - payment
  /api/v1/oauth/callback:
    post:
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/oauth.CallbackRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - oauth
  /api/v1/oauth/login:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - oauth
  /api/v1/oauth/logout:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - oauth
  /api/v1/oauth/user-info:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - oauth
  /api/v1/order/transactions:
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: request
        schema:
          $ref: '#/definitions/order.TransactionListRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - order
  /api/v1/user/pay-key:
    put:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.UpdatePayKeyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.ResponseAny'
      tags:
      - user
swagger: "2.0"
